spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://compassionate_babbage:3306/geo_db?useSSL=false
        username: root
        password: 1234

mybatis:
    mapper-locations: classpath:sql/**/*.xml
    type-aliases-package: com.spring.geo.**.model
    configuration:
        map-underscore-to-camel-case: true
        jdbc-type-for-null: 'NULL'
        call-setters-on-nulls: true